import { strict as assert } from "node:assert";
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

import {
  BUNDLED_DEV_DEPENDENCIES,
  NOTICES_FILE,
  bundledDevPackages,
  noticeFiles,
  packagesFrom,
  renderNotices,
  scanBundle,
  unlistedBundled,
} from "./notices.mjs";

const root = fileURLToPath(new URL("../", import.meta.url));

function fixture() {
  const dir = mkdtempSync(join(tmpdir(), "armadra-notices-"));
  const pkg = (name, files) => {
    const path = join(dir, name.replace("/", "+"));
    mkdirSync(path, { recursive: true });
    for (const [file, text] of Object.entries(files))
      writeFileSync(join(path, file), text);
    return path;
  };
  return { dir, pkg };
}

test("license and notice files are read in name order, CRLF and trailing blanks normalised", () => {
  const { dir, pkg } = fixture();
  try {
    const path = pkg("a", {
      "LICENSE.md": "\uFEFFMIT License\r\n\r\nCopyright (c) A   \r\n\r\n",
      NOTICE: "Apache notice\n",
      "README.md": "not a notice",
      "license-other.txt": "",
    });
    assert.deepEqual(noticeFiles(path), [
      { name: "LICENSE.md", text: "MIT License\n\nCopyright (c) A" },
      { name: "NOTICE", text: "Apache notice" },
    ]);
    assert.deepEqual(noticeFiles(join(dir, "missing")), []);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("pnpm's grouped listing becomes one sorted row per installed version, workspace packages left out", () => {
  const rows = packagesFrom({
    MIT: [
      { name: "zeta", versions: ["1.0.0"], paths: ["/z"], license: "MIT" },
      {
        name: "alpha",
        versions: ["2.0.0", "1.0.0"],
        paths: ["/a2", "/a1"],
        license: "MIT",
        author: "A",
      },
      { name: "@armadra/shared", versions: ["0.1.0"], paths: ["/s"] },
    ],
    "Apache-2.0": [{ name: "beta", versions: ["3.0.0"], paths: ["/b"] }],
  });
  assert.deepEqual(
    rows.map((row) => `${row.name}@${row.version} ${row.license} ${row.path}`),
    [
      "alpha@1.0.0 MIT /a1",
      "alpha@2.0.0 MIT /a2",
      "beta@3.0.0 Apache-2.0 /b",
      "zeta@1.0.0 MIT /z",
    ],
  );
});

test("the rendered notices carry full texts, Electron/Chromium and ama pointers, and no absolute paths", () => {
  const { dir, pkg } = fixture();
  try {
    const withLicense = pkg("dep", {
      LICENSE: "Copyright (c) Dep\n```\nfenced\n```\n",
    });
    const bare = pkg("bare", {});
    const text = renderNotices({
      listing: {
        MIT: [
          {
            name: "dep",
            versions: ["1.2.3"],
            paths: [withLicense],
            license: "MIT",
            homepage: "https://example.test/dep",
          },
        ],
        Unknown: [{ name: "bare", versions: ["0.0.1"], paths: [bare] }],
      },
      agentVersion: "0.6.5",
    });
    assert.match(text, /^# Third-party notices\n/);
    assert.match(text, /LICENSE\.electron\.txt/);
    assert.match(text, /LICENSES\.chromium\.html/);
    assert.match(text, /`@armadra\/agent` 0\.6\.5/);
    assert.match(text, /## npm packages \(2\)/);
    assert.match(
      text,
      /### dep@1\.2\.3\n\nLicense: MIT\nHomepage: https:\/\/example\.test\/dep/,
    );
    // A license text containing ``` is wrapped in a longer fence.
    assert.match(text, /````text\nCopyright \(c\) Dep\n```\nfenced\n```\n````/);
    assert.match(
      text,
      /### bare@0\.0\.1\n\nLicense: Unknown\n\nThe package ships no license file/,
    );
    assert.ok(!text.includes(dir), "absolute install paths must not leak");
    assert.ok(text.endsWith("\n") && !text.endsWith("\n\n"));
    assert.ok(!text.includes("\r"));
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("the committed notices are the generated shape (the byte comparison is `--check` in pnpm check)", () => {
  const committed = readFileSync(join(root, NOTICES_FILE), "utf8");
  assert.match(committed, /^# Third-party notices\n/);
  assert.match(committed, /Generated by `node tools\/notices\.mjs`/);
  assert.match(committed, /### node-pty@/);
  // node-pty's copyright lines (external-services §11.3) come through verbatim.
  assert.match(committed, /Christopher Jeffrey/);
  assert.match(committed, /Microsoft Corporation/);
});

test("the build is scanned for bundled packages: JS #region paths and CSS banners", () => {
  const { dir } = fixture();
  try {
    const repo = join(dir, "repo");
    const store = join(
      repo,
      "node_modules/.pnpm/left-pad@1.3.0/node_modules/left-pad",
    );
    const scoped = join(
      repo,
      "node_modules/.pnpm/@scope+thing@2.0.0/node_modules/@scope/thing",
    );
    for (const [path, version] of [
      [store, "1.3.0"],
      [scoped, "2.0.0"],
    ]) {
      mkdirSync(path, { recursive: true });
      writeFileSync(join(path, "package.json"), JSON.stringify({ version }));
    }
    const out = join(repo, "apps/desktop/out");
    mkdirSync(join(out, "core"), { recursive: true });
    mkdirSync(join(out, "renderer/assets"), { recursive: true });
    writeFileSync(
      join(out, "core/main.js"),
      [
        "//#region \\0rolldown/runtime.js",
        "//#endregion",
        "//#region ../../node_modules/.pnpm/left-pad@1.3.0/node_modules/left-pad/index.js",
        "//#endregion",
        "//#region ../../node_modules/.pnpm/@scope+thing@2.0.0/node_modules/@scope/thing/dist/a.js",
        "//#region ../../node_modules/.pnpm/@scope+thing@2.0.0/node_modules/@scope/thing/dist/b.js",
        "//#region src/core/main.ts",
      ].join("\n"),
    );
    writeFileSync(
      join(out, "renderer/assets/index.css"),
      "/*! tailwindcss v4.3.3 | MIT License | https://tailwindcss.com */\n:root{}",
    );
    const scanned = scanBundle(out, { resolveFrom: repo });
    assert.deepEqual(scanned, [
      { name: "@scope/thing", version: "2.0.0" },
      { name: "left-pad", version: "1.3.0" },
      { name: "tailwindcss", version: "4.3.3" },
    ]);
    const listing = {
      MIT: [{ name: "left-pad", versions: ["1.3.0"], paths: [store] }],
    };
    assert.deepEqual(
      unlistedBundled({ scanned, listing }).map((p) => p.name),
      ["@scope/thing", "tailwindcss"],
    );
    assert.deepEqual(
      unlistedBundled({
        scanned,
        listing,
        bundled: [
          { name: "@scope/thing", version: "2.0.0" },
          { name: "tailwindcss", version: "4.3.3" },
        ],
      }),
      [],
    );
    // A different installed version is not covered by the listed one.
    assert.equal(
      unlistedBundled({
        scanned: [{ name: "left-pad", version: "1.4.0" }],
        listing,
      }).length,
      1,
    );
    // The workspace's own packages are never third-party.
    assert.deepEqual(
      unlistedBundled({
        scanned: [{ name: "@armadra/agent", version: "0.6.7" }],
        listing,
      }),
      [],
    );
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("bundled devDependencies are read from their installs and rendered beside the production ones", () => {
  const bundled = bundledDevPackages();
  assert.deepEqual(
    bundled.map((p) => p.name),
    BUNDLED_DEV_DEPENDENCIES.map((p) => p.name),
  );
  for (const pkg of bundled) {
    assert.match(pkg.version, /^\d+\.\d+\.\d+/);
    assert.notEqual(pkg.license, "Unknown");
  }
  const text = renderNotices({
    listing: {},
    bundled: [{ ...bundled[0] }, { ...bundled[0] }],
    read: () => [{ name: "LICENSE", text: "MIT text" }],
  });
  assert.equal(text.split(`### ${bundled[0].name}@`).length - 1, 1);
  const committed = readFileSync(join(root, NOTICES_FILE), "utf8");
  for (const pkg of bundled)
    assert.ok(committed.includes(`### ${pkg.name}@${pkg.version}`), pkg.name);
});
