/**
 * THIRD_PARTY_NOTICES.md：随发行包分发的第三方声明（外部服务 §11.3）。
 *
 *   node tools/notices.mjs            重新生成根目录的 THIRD_PARTY_NOTICES.md
 *   node tools/notices.mjs --check    与仓库里的那份逐字节比较，不同就失败
 *
 * 来源是 `pnpm licenses list --prod --json`：工作区所有包的生产依赖。每个包的
 * 许可证正文从它安装目录里的 LICENSE / NOTICE 等文件原样读出——MIT、BSD、
 * Apache 都要求随二进制带上版权行与许可证全文，只写一个 SPDX 缩写不够。
 *
 * 不在 npm 生产依赖里、但同样随包分发的三样东西在文件开头单列：Electron 与
 * Chromium 的声明由 `apps/desktop/scripts/after-pack.mjs` 放在可执行文件旁
 * （macOS 是 `Contents/Resources/`），`@armadra/agent`（ama）自带的声明随
 * `resources/agent/` 一起带，Armadra 自己的 LICENSE。
 *
 * 输出只取决于锁文件装出来的东西：按名字与版本排序，不写绝对路径与时间，
 * 换行统一为 LF。所以 `--check` 能在三个平台的 CI 上防漂移——依赖变了却没有
 * 重新生成，`pnpm check` 就红。
 */
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));

export const NOTICES_FILE = "THIRD_PARTY_NOTICES.md";

/** 包目录里算作「声明」的文件：LICENSE / LICENCE / COPYING / NOTICE 及其扩展名变体。 */
const NOTICE_NAME = /^(licen[cs]e|copying|notice)([-._].*)?$/i;

/** 随 Electron 二进制分发、after-pack.mjs 负责放进包里的两份声明。 */
export const ELECTRON_NOTICES = [
  "LICENSE.electron.txt",
  "LICENSES.chromium.html",
];

/** 跑 `pnpm licenses list --prod --json`，返回解析后的对象。 */
export function pnpmLicenses(cwd = root) {
  const result = spawnSync("pnpm", ["licenses", "list", "--prod", "--json"], {
    cwd,
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
    // Windows 上 pnpm 是 .cmd，不经 shell 起不来。
    shell: process.platform === "win32",
  });
  if (result.status !== 0)
    throw new Error(
      `pnpm licenses list failed (${result.status}): ${result.stderr || result.error?.message || ""}`,
    );
  return JSON.parse(result.stdout);
}

/** 把一段文本统一成 LF、去掉行尾空白与首尾空行。 */
function normalize(text) {
  return text
    .replace(/^\uFEFF/, "")
    .replace(/\r\n?/g, "\n")
    .split("\n")
    .map((line) => line.replace(/\s+$/, ""))
    .join("\n")
    .trim();
}

/** 一个包目录里的声明文件，按名字排序；`[{name, text}]`。 */
export function noticeFiles(directory) {
  if (!existsSync(directory)) return [];
  return readdirSync(directory, { withFileTypes: true })
    .filter((entry) => entry.isFile() && NOTICE_NAME.test(entry.name))
    .map((entry) => entry.name)
    .sort()
    .map((name) => ({
      name,
      text: normalize(readFileSync(join(directory, name), "utf8")),
    }))
    .filter((file) => file.text !== "");
}

/**
 * `pnpm licenses list --json` 的输出（按许可证分组）→ 按名字、版本排好的包表。
 *
 * 一个名字装了几个版本时 pnpm 给的是并列的 `versions` 与 `paths`，这里拆成
 * 每个版本一条，各读各的声明。工作区自己的 `@armadra/*` 不算第三方。
 */
export function packagesFrom(listing) {
  const packages = [];
  for (const [license, entries] of Object.entries(listing)) {
    for (const entry of entries) {
      if (entry.name.startsWith("@armadra/")) continue;
      entry.versions.forEach((version, index) => {
        packages.push({
          name: entry.name,
          version,
          license: entry.license ?? license,
          author: typeof entry.author === "string" ? entry.author : "",
          homepage: entry.homepage ?? "",
          path: entry.paths?.[index] ?? entry.paths?.[0] ?? "",
        });
      });
    }
  }
  return packages.sort(
    (a, b) =>
      (a.name < b.name ? -1 : a.name > b.name ? 1 : 0) ||
      (a.version < b.version ? -1 : a.version > b.version ? 1 : 0),
  );
}

/** 比正文里最长的反引号串多一个，正文里有 ``` 也不会提前闭合。 */
function fenceFor(text) {
  const longest = Math.max(
    0,
    ...[...text.matchAll(/`+/g)].map((match) => match[0].length),
  );
  return "`".repeat(Math.max(3, longest + 1));
}

/** 读某个已安装包的版本；没装就是 ""。 */
function installedVersion(directory) {
  const manifest = join(directory, "package.json");
  if (!existsSync(manifest)) return "";
  return JSON.parse(readFileSync(manifest, "utf8")).version ?? "";
}

/**
 * 生成 THIRD_PARTY_NOTICES.md 的全文。
 *
 * `listing` 是 `pnpm licenses list --prod --json` 的结果；`agentVersion` 是随包
 * 打进 `resources/agent/` 的 `@armadra/agent` 版本（它是桌面壳的 devDependency，
 * 不在 `--prod` 里，自带声明文件）。
 */
export function renderNotices({
  listing,
  agentVersion = "",
  read = noticeFiles,
}) {
  const packages = packagesFrom(listing);
  const lines = [
    "# Third-party notices",
    "",
    "<!-- Generated by `node tools/notices.mjs` from `pnpm licenses list --prod --json`. Do not edit by hand; `node tools/notices.mjs --check` runs in `pnpm check`. -->",
    "",
    "Armadra is distributed under the MIT License (see `LICENSE`). It includes the third-party software listed below.",
    "",
    "## Shipped beside the application",
    "",
    "- **Electron and Chromium.** The notices Electron and Chromium require to accompany their binaries are shipped as `LICENSE.electron.txt` and `LICENSES.chromium.html` next to the executable (on macOS in `Armadra.app/Contents/Resources/`).",
  ];
  if (agentVersion)
    lines.push(
      `- **ama (\`@armadra/agent\` ${agentVersion}).** Its own license and third-party notices are shipped in \`resources/agent/\` as \`LICENSE\` and \`THIRD_PARTY_NOTICES.md\`.`,
    );
  lines.push("", `## npm packages (${packages.length})`, "");
  for (const pkg of packages) {
    lines.push(`### ${pkg.name}@${pkg.version}`, "", `License: ${pkg.license}`);
    if (pkg.author) lines.push(`Author: ${normalize(pkg.author)}`);
    if (pkg.homepage) lines.push(`Homepage: ${pkg.homepage}`);
    lines.push("");
    const files = read(pkg.path);
    if (files.length === 0) {
      lines.push(
        "The package ships no license file; see its homepage for the license terms.",
        "",
      );
      continue;
    }
    for (const file of files) {
      const fence = fenceFor(file.text);
      lines.push(`${file.name}:`, "", `${fence}text`, file.text, fence, "");
    }
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

/** 生成当前检出的声明全文。 */
export function currentNotices(cwd = root) {
  return renderNotices({
    listing: pnpmLicenses(cwd),
    agentVersion: installedVersion(
      join(cwd, "apps/desktop/node_modules/@armadra/agent"),
    ),
  });
}

function main(argv) {
  const target = join(root, NOTICES_FILE);
  const expected = currentNotices(root);
  if (argv.includes("--check")) {
    const actual = existsSync(target)
      ? readFileSync(target, "utf8").replace(/\r\n/g, "\n")
      : "";
    if (actual !== expected) {
      console.error(
        `${NOTICES_FILE} is out of date with the installed dependencies; run \`node tools/notices.mjs\` and commit the result.`,
      );
      return 1;
    }
    console.log(`${NOTICES_FILE} is up to date`);
    return 0;
  }
  writeFileSync(target, expected);
  console.log(`wrote ${NOTICES_FILE}`);
  return 0;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  process.exit(main(process.argv.slice(2)));
}
