import {
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import {
  basename,
  dirname,
  isAbsolute,
  join,
  relative,
  delimiter,
  sep,
} from "node:path";
import {
  definition,
  launchTargetOf,
  resolveCommand,
} from "../../agent/registry";
import type { ShimTarget } from "../../agent/windows-shim";
import { LAUNCH_GATE, type LauncherSpec } from "./launcher";

export { LAUNCH_GATE };

/**
 * The Windows half of the canvas launcher (docs/design/canvas-launcher.md
 * §5, §6.1): what goes into `<data>/integration/run\` and `shims\`.
 *
 * Each injected CLI gets two copies of one small console program,
 * `armadra-launch.exe` (`cli/armadra-launch/windows-launch.cs`, built by
 * `scripts/launch-exe.mjs`), each beside a `.launch` of the same name:
 *
 *   * `run\<cli>.exe` — the launcher. The typed line is
 *     `run\claude.exe <program> [lead…] <flags…>`; the first word after it is
 *     the program, and the caller's command line goes to `CreateProcess`
 *     untouched with the injected words appended.
 *   * `shims\<cli>.exe` — the shim, first on a canvas terminal's `PATH`, so a
 *     hand-typed `claude` hits it. Its `.launch` also names the program and
 *     its lead words — resolved here, because unwrapping npm's `.cmd` lives in
 *     TypeScript (`agent/windows-shim.ts`), not in C# (§5.4).
 *
 * Both inject only when `ARMADRA_NODE_ID` is set; without it they start the
 * program as asked. The injected argv and environment are literals in the
 * `.launch`, never read by a shell.
 *
 * Pure apart from {@link windowsLauncherFiles} reading the `.exe`,
 * {@link shimTargetFor} probing `PATH`, and {@link writeWindowsLauncherFiles}.
 */

/** The program's file name in a build's resources (`cli/armadra-launch.exe`). */
export const LAUNCH_EXE_NAME = "armadra-launch.exe";
/** The first line of every `.launch`; the program refuses anything else. */
export const LAUNCH_CONFIG_HEADER = "armadra-launch 1";
/**
 * What a `.launch` needs from the generator's spec: the injection's literal
 * argv (appended after the caller's words), its environment (set for the
 * CLI process only), and the node credential / ama key exchange the POSIX
 * launcher does with `armadra-hook credential` (contract §20.4, §12.4). Any
 * `LauncherSpec` fits.
 */
export type LaunchConfigSpec = Pick<LauncherSpec, "agentId" | "args" | "env"> &
  Partial<Pick<LauncherSpec, "credential" | "amaKeys">>;

/**
 * Everything one CLI's Windows launcher and shim are made of: the POSIX
 * generator's `LauncherSpec` (§6.1) plus the program and the shim's target.
 */
export interface WindowsLauncherSpec extends LauncherSpec {
  /** The built `armadra-launch.exe` ({@link findLaunchExe}). */
  readonly exe: string;
  /** The shim's program and lead words ({@link shimTargetFor}); absent, no shim is written. */
  readonly shimTarget?: ShimTarget;
}

/** One generated file: its bytes and the mode it is written with. */
export interface LauncherFile {
  readonly content: string | Buffer;
  readonly mode: number;
}

const ENV_NAME = /^[A-Za-z_][A-Za-z0-9_]*$/;
const LINE_BREAK = /[\r\n]/;

function literal(what: string, value: string): string {
  if (LINE_BREAK.test(value)) {
    throw new Error(
      `${what} cannot hold a line break: ${JSON.stringify(value)}`,
    );
  }
  return value;
}

/**
 * The `.launch` text for one CLI: the header, the gate, in shim mode the
 * program and its lead words, then every `env=` and `arg=`. Values are written
 * as they are — no quoting, no escaping — so a value holding a line break is
 * refused (Codex's `developer_instructions` carries `\n` as two characters,
 * not a newline). Deterministic: the same spec gives the same bytes.
 */
export function launchConfig(
  spec: LaunchConfigSpec,
  mode: "run" | "shim",
  target?: ShimTarget,
): string {
  const agentId = literal("an agent id", spec.agentId);
  const lines = [
    LAUNCH_CONFIG_HEADER,
    `# Armadra ${mode === "run" ? "canvas launcher" : "canvas shim"} (${agentId}). Generated by the core; edits are overwritten.`,
    `gate=${LAUNCH_GATE}`,
  ];
  if (mode === "shim") {
    if (target === undefined) {
      throw new Error(`the ${agentId} shim needs a program to start`);
    }
    if (target.program === "") {
      throw new Error(`the ${agentId} shim's program is empty`);
    }
    lines.push(`program=${literal("a program", target.program)}`);
    for (const word of target.args)
      lines.push(`lead=${literal("a lead word", word)}`);
  }
  for (const [name, value] of spec.env) {
    if (!ENV_NAME.test(name)) {
      throw new Error(`not an environment variable name: ${name}`);
    }
    lines.push(`env=${name}=${literal(`${name}'s value`, value)}`);
  }
  for (const word of spec.args)
    lines.push(`arg=${literal("an argument", word)}`);
  // The exchange, as in `launcher.ts::credentialLines` / `amaKeyLines`: an
  // empty client with variables still writes `credential=` so a bound
  // credential is refused rather than skipped; ama keys need a client.
  const credential = spec.credential;
  if (credential !== undefined && credential.variables.length > 0) {
    lines.push(
      `credential=${literal("the credential client", credential.client)}`,
    );
    for (const name of credential.variables)
      lines.push(`credential-var=${variableName(name)}`);
  }
  const keys = spec.amaKeys;
  if (keys !== undefined && keys.client !== "" && keys.variables.length > 0) {
    lines.push(`ama-keys=${literal("the ama key client", keys.client)}`);
    for (const name of keys.variables)
      lines.push(`ama-var=${variableName(name)}`);
  }
  return `${lines.join("\r\n")}\r\n`;
}

function variableName(name: string): string {
  if (!ENV_NAME.test(name)) {
    throw new Error(`not an environment variable name: ${name}`);
  }
  return name;
}

/** `run\<cli>.exe` — the launcher the typed line names. */
export function windowsLauncherPath(runDir: string, agentId: string): string {
  return join(runDir, `${agentId}.exe`);
}

/** `shims\<cli>.exe` — the shim a hand-typed name hits. */
export function windowsShimPath(shimDir: string, agentId: string): string {
  return join(shimDir, `${agentId}.exe`);
}

/**
 * Every file of one CLI's Windows launcher, by absolute path: `run\<cli>.exe`
 * and `.launch`, plus `shims\<cli>.exe` and `.launch` when the spec has a
 * shim target. The `.exe` is a copy of {@link WindowsLauncherSpec.exe} (not a
 * link: Windows refuses to overwrite a running image but lets it be renamed,
 * which {@link writeWindowsLauncherFiles} relies on). Throws when the `.exe`
 * cannot be read — the caller checks {@link findLaunchExe} first and writes no
 * launcher at all without it (§5.3).
 */
export function windowsLauncherFiles(
  spec: WindowsLauncherSpec,
): Map<string, LauncherFile> {
  const exe = readFileSync(spec.exe);
  const files = new Map<string, LauncherFile>();
  const run = windowsLauncherPath(spec.runDir, spec.agentId);
  files.set(run, { content: exe, mode: 0o755 });
  files.set(configPathOf(run), {
    content: launchConfig(spec, "run"),
    mode: 0o644,
  });
  if (spec.shimTarget !== undefined) {
    const shim = windowsShimPath(spec.shimDir, spec.agentId);
    files.set(shim, { content: exe, mode: 0o755 });
    files.set(configPathOf(shim), {
      content: launchConfig(spec, "shim", spec.shimTarget),
      mode: 0o644,
    });
  }
  return files;
}

/** `x\claude.exe` → `x\claude.launch`, where the program looks for it. */
function configPathOf(exe: string): string {
  return `${exe.slice(0, -".exe".length)}.launch`;
}

/* ------------------------------ shim target ------------------------------- */

export interface ShimTargetOptions {
  /** The environment whose `PATH` is searched; defaults to this process'. */
  readonly ambient?: NodeJS.ProcessEnv;
  /**
   * The shims directory. Left out of the search, so a shim can never be
   * resolved to itself (a terminal started from a canvas node has it first).
   */
  readonly shimDir?: string;
}

/**
 * What `shims\<cli>.exe` starts (§5.4): the CLI as the canvas would resolve it
 * — `resolveCommand` on the agent `PATH`, then `launchTargetOf` to step past
 * an npm / pnpm `.cmd` wrapper to `node.exe <cli.js>`. A native program, or a
 * wrapper that could not be read, is its own target with no lead words (the
 * launcher starts a `.cmd` through `cmd.exe`). `undefined` when the CLI is not
 * found, or for an id that is not a built-in CLI: then no shim is written and
 * a hand-typed name hits the next one on `PATH`, uninjected.
 *
 * Resolved when a canvas terminal is about to start, so a changed install
 * (another node version) is picked up by the next terminal.
 */
export function shimTargetFor(
  agentId: string,
  options: ShimTargetOptions = {},
): ShimTarget | undefined {
  const command = definition(agentId)?.launchCmd;
  if (command === undefined) return undefined;
  const ambient = options.ambient ?? process.env;
  const env =
    options.shimDir === undefined
      ? ambient
      : withPath(ambient, withoutDirectory(pathOf(ambient), options.shimDir));
  const resolved = resolveCommand(command, env);
  if (resolved === undefined) return undefined;
  if (options.shimDir !== undefined && inside(options.shimDir, resolved)) {
    return undefined;
  }
  return launchTargetOf(resolved, env) ?? { program: resolved, args: [] };
}

/** `PATH` however it is spelt (`Path` on Windows), or `""`. */
function pathOf(env: NodeJS.ProcessEnv): string {
  if (env.PATH !== undefined) return env.PATH;
  const key = Object.keys(env).find((name) => name.toUpperCase() === "PATH");
  return key === undefined ? "" : (env[key] ?? "");
}

function withPath(env: NodeJS.ProcessEnv, path: string): NodeJS.ProcessEnv {
  const copy: NodeJS.ProcessEnv = {};
  for (const [name, value] of Object.entries(env)) {
    if (name.toUpperCase() !== "PATH") copy[name] = value;
  }
  copy.PATH = path;
  return copy;
}

/** `PATH` without `directory` (case-insensitive, trailing separators ignored). */
export function withoutDirectory(path: string, directory: string): string {
  const target = normalized(directory);
  return path
    .split(delimiter)
    .filter((entry) => entry === "" || normalized(entry) !== target)
    .join(delimiter);
}

function normalized(directory: string): string {
  return directory
    .trim()
    .replace(/^"|"$/g, "")
    .replace(/[\\/]+$/, "")
    .toLowerCase();
}

function inside(directory: string, file: string): boolean {
  const rel = relative(directory, file);
  return (
    rel === "" ||
    (rel !== ".." && !rel.startsWith(`..${sep}`) && !isAbsolute(rel))
  );
}

/* --------------------------------- program -------------------------------- */

/** Where a built `armadra-launch.exe` can be, in the order they are tried. */
export function defaultLaunchExeCandidates(): string[] {
  const candidates: string[] = [];
  if (process.resourcesPath !== undefined) {
    candidates.push(join(process.resourcesPath, "cli", LAUNCH_EXE_NAME));
  }
  candidates.push(join(dirname(process.execPath), "cli", LAUNCH_EXE_NAME));
  // `out/core/main.js` → `out/cli/armadra-launch.exe`, which
  // `pnpm --filter @armadra/desktop build` compiles on a Windows host.
  candidates.push(join(__dirname, "..", "cli", LAUNCH_EXE_NAME));
  return candidates;
}

/**
 * The built `armadra-launch.exe`, or `undefined` — a development tree not
 * built on Windows, or a package made where `csc` was missing. Without it the
 * core writes no `run\` / `shims\` and launches on a bare line (§5.3).
 */
export function findLaunchExe(
  candidates: readonly string[] = defaultLaunchExeCandidates(),
): string | undefined {
  return candidates.find(isFile);
}

/**
 * The `armadra-launch.exe` this core would copy into `run\` and `shims\`:
 * `override`, else `ARMADRA_LAUNCH_EXE`, else the built one next to the app
 * ({@link findLaunchExe}). An empty override means "none"; an override that
 * is not a file is none as well — never a guess at another one.
 */
export function configuredLaunchExe(
  env: NodeJS.ProcessEnv = process.env,
  override?: string,
): string | undefined {
  const value = override ?? env.ARMADRA_LAUNCH_EXE;
  if (value === undefined) return findLaunchExe();
  return isFile(value) ? value : undefined;
}

function isFile(file: string): boolean {
  try {
    return statSync(file).isFile();
  } catch {
    return false;
  }
}

/**
 * Writes {@link windowsLauncherFiles}' output and returns the paths whose bytes
 * changed. An identical file is left alone. A changed `.exe` that is running
 * (a canvas agent started through it) cannot be overwritten but can be
 * renamed, so it is moved aside first; leftovers of an earlier move are
 * removed on the way, quietly failing while they still run — the same as the
 * hook launcher's `placeExe`.
 */
export function writeWindowsLauncherFiles(
  files: ReadonlyMap<string, LauncherFile>,
): string[] {
  const changed: string[] = [];
  for (const [file, { content, mode }] of files) {
    const wanted =
      typeof content === "string" ? Buffer.from(content, "utf8") : content;
    mkdirSync(dirname(file), { recursive: true });
    if (file.toLowerCase().endsWith(".exe")) removeAside(file);
    try {
      if (wanted.equals(readFileSync(file))) continue;
    } catch {
      // Not there yet.
    }
    try {
      writeFileSync(file, wanted, { mode });
    } catch (error) {
      const code = (error as NodeJS.ErrnoException).code;
      if (code !== "EBUSY" && code !== "EPERM") throw error;
      renameSync(file, `${file}.old-${process.pid}-${Date.now()}`);
      writeFileSync(file, wanted, { mode });
    }
    changed.push(file);
  }
  return changed;
}

function removeAside(file: string): void {
  const directory = dirname(file);
  const prefix = `${basename(file)}.old-`;
  let names: string[];
  try {
    names = readdirSync(directory);
  } catch {
    return;
  }
  for (const name of names) {
    if (!name.startsWith(prefix)) continue;
    try {
      rmSync(join(directory, name), { force: true });
    } catch {
      // Still running; the next write gets it.
    }
  }
}
