import {
  HOOK_CLIENT_REVISION,
  INTEGRATION_REVISION,
  MOD_REVISION,
} from "../events";
import { jsString } from "../extension-template";
import { COMMAND_DECLARATIONS, COMMAND_REGISTRATIONS } from "./commands";
import { STATUS_DECLARATIONS, STATUS_REGISTRATIONS } from "./status";
import { TRANSPORT_DECLARATIONS } from "./transport";
import type { ModLocale } from "./i18n";
import { UI_DECLARATIONS, UI_REGISTRATIONS, UI_TYPES } from "./ui";

/**
 * The Claude Code mod: a plugin of function hooks Claude Code loads from a
 * second `--plugin-dir` (contract §57, docs/design/canvas-only-integration.md
 * §3). Three files under `<data>/integration/claude/mod/`, the manifest named
 * `armadra-mod`, generated here and written by `inject.ts` — at every core
 * start from scratch, and byte-compared on every launch after.
 *
 * Deterministic, like the Pi extension: the same client and revision produce
 * the same bytes, so a regeneration that changed nothing writes nothing (an
 * interactive session watches the folder and would reload the module).
 *
 * The module is built from segments, each its own file, so the packages that
 * add the band (`ui.ts`) and the slash commands (`commands.ts`) do not edit
 * the same lines: declarations first, then one `register` holding every
 * segment's registrations in order.
 */

/** The manifest's name: a second plugin beside the skill plugin `armadra`. */
export const MOD_PLUGIN_NAME = "armadra-mod";

/** The hooks module's file name under `hooks/`. */
export const MOD_MODULE_FILE = "armadra.ts";

/**
 * The state contract's path under the mod folder, as the manifest names it:
 * beside the module, armadra-named like every file we hand a CLI, and clear
 * of `.claude-plugin/types/`, which is Claude Code's own.
 */
export const MOD_TYPES_FILE = "hooks/armadra-state.d.ts";

/** What the generated module may vary by besides the hook client. */
export interface ClaudeModOptions {
  /** `ui.locale` (contract §57.6); the words of the slash commands (M3). */
  readonly locale?: ModLocale;
}

const HEADER = `// Armadra — Claude Code mod (${MOD_PLUGIN_NAME}).
// Generated by the Armadra core and rewritten at every start; edits are lost.
//
// Reports this session's hook events to the local Armadra core over the same
// socket, headers and body as the armadra-hook client, shows the canvas
// node's and board's names in the status line, and, in an interactive
// terminal, its links and unread count above the prompt (names and numbers). Outside a canvas terminal ARMADRA_NODE_ID
// is unset and every hook only passes its event on.
//
// It never answers a permission prompt, never refuses or rewrites a tool
// call, never adds to the conversation: every hook calls next(e) with the
// event it was given. Every path is wrapped; a canvas problem must not become
// a session problem.
import type { EngineInterface, Register, RenderElement, SessionStartInput } from "claude-code";
import type { ArmadraModLink, ArmadraModOverlay } from "./armadra-state";
`;

/** `hooks/armadra.ts`: the whole module, for the hook client at `clientBin`. */
export function claudeModSource(
  clientBin: string,
  _options: ClaudeModOptions = {}, // the M3 segment reads the locale
): string {
  return (
    `${HEADER}\n` +
    `const ARMADRA_CLIENT = "${jsString(clientBin)}";\n` +
    `const ARMADRA_CLIENT_REVISION = "${HOOK_CLIENT_REVISION}";\n` +
    `const ARMADRA_MOD_REVISION = ${MOD_REVISION};\n` +
    TRANSPORT_DECLARATIONS +
    STATUS_DECLARATIONS +
    UI_DECLARATIONS +
    COMMAND_DECLARATIONS +
    "\nexport const register: Register = (on) => {" +
    STATUS_REGISTRATIONS +
    UI_REGISTRATIONS +
    COMMAND_REGISTRATIONS +
    "};\n"
  );
}

/** `.claude-plugin/plugin.json`. */
export function claudeModManifest(): Record<string, unknown> {
  return {
    name: MOD_PLUGIN_NAME,
    description: "Armadra canvas status — loaded only for canvas nodes.",
    version: String(INTEGRATION_REVISION),
    author: { name: "Armadra" },
    types: `./${MOD_TYPES_FILE}`,
  };
}

/** `hooks/armadra-state.d.ts`: the state contract `claude plugin validate` checks. */
export function claudeModTypes(): string {
  return UI_TYPES;
}

/** `hooks/hooks.json`: the one hooks module. */
export function claudeModHooks(): Record<string, unknown> {
  return { modules: [`./${MOD_MODULE_FILE}`] };
}
