import {
  HOOK_CLIENT_REVISION,
  INTEGRATION_REVISION,
  MOD_REVISION,
} from "../events";
import { jsString } from "../extension-template";
import { COMMAND_DECLARATIONS, COMMAND_REGISTRATIONS } from "./commands";
import { STATUS_DECLARATIONS, STATUS_REGISTRATIONS } from "./status";
import { TRANSPORT_DECLARATIONS } from "./transport";
import { UI_DECLARATIONS, UI_REGISTRATIONS } from "./ui";

/**
 * The Claude Code mod: a plugin of function hooks Claude Code loads from a
 * second `--plugin-dir` (contract §55, docs/design/canvas-only-integration.md
 * §3). Three files under `<data>/integration/claude/mod/`, the manifest named
 * `armadra-mod`, generated here and written by `inject.ts` — at every core
 * start from scratch, and byte-compared on every launch after.
 *
 * Deterministic, like the Pi extension: the same client and revision produce
 * the same bytes, so a regeneration that changed nothing writes nothing (an
 * interactive session watches the folder and would reload the module).
 *
 * The module is built from segments, each its own file, so the packages that
 * add the band (`ui.ts`) and the slash commands (`commands.ts`) do not edit
 * the same lines: declarations first, then one `register` holding every
 * segment's registrations in order.
 */

/** The manifest's name: a second plugin beside the skill plugin `armadra`. */
export const MOD_PLUGIN_NAME = "armadra-mod";

/** The hooks module's file name under `hooks/`. */
export const MOD_MODULE_FILE = "armadra.ts";

const HEADER = `// Armadra — Claude Code mod (${MOD_PLUGIN_NAME}).
// Generated by the Armadra core and rewritten at every start; edits are lost.
//
// Reports this session's hook events to the local Armadra core over the same
// socket, headers and body as the armadra-hook client, and shows the canvas
// node's name in the status line. Outside a canvas terminal ARMADRA_NODE_ID
// is unset and every hook only passes its event on.
//
// It never answers a permission prompt, never refuses or rewrites a tool
// call, never adds to the conversation: every hook calls next(e) with the
// event it was given. Every path is wrapped; a canvas problem must not become
// a session problem.
import type { EngineInterface, Register, SessionStartInput } from "claude-code";
`;

/** `hooks/armadra.ts`: the whole module, for the hook client at `clientBin`. */
export function claudeModSource(clientBin: string): string {
  return (
    `${HEADER}\n` +
    `const ARMADRA_CLIENT = "${jsString(clientBin)}";\n` +
    `const ARMADRA_CLIENT_REVISION = "${HOOK_CLIENT_REVISION}";\n` +
    `const ARMADRA_MOD_REVISION = ${MOD_REVISION};\n` +
    TRANSPORT_DECLARATIONS +
    STATUS_DECLARATIONS +
    UI_DECLARATIONS +
    COMMAND_DECLARATIONS +
    "\nexport const register: Register = (on) => {" +
    STATUS_REGISTRATIONS +
    UI_REGISTRATIONS +
    COMMAND_REGISTRATIONS +
    "};\n"
  );
}

/** `.claude-plugin/plugin.json`. */
export function claudeModManifest(): Record<string, unknown> {
  return {
    name: MOD_PLUGIN_NAME,
    description: "Armadra canvas status — loaded only for canvas nodes.",
    version: String(INTEGRATION_REVISION),
    author: { name: "Armadra" },
  };
}

/** `hooks/hooks.json`: the one hooks module. */
export function claudeModHooks(): Record<string, unknown> {
  return { modules: [`./${MOD_MODULE_FILE}`] };
}
